import {
  Activity,
  BookOpen,
  Boxes,
  Bug,
  ClipboardList,
  Code,
  Coffee,
  Command,
  Container,
  Database,
  Eye,
  Frame,
  Gauge,
  Gem,
  GitBranch,
  GitPullRequest,
  Hash,
  Hexagon,
  KeyRound,
  LayoutGrid,
  MessageCircle,
  Monitor,
  Package,
  Package2,
  PackageCheck,
  Palette,
  Rocket,
  Scissors,
  ShieldCheck,
  Ship,
  Smartphone,
  Stethoscope,
  Terminal,
  Users,
  Zap,
  type LucideIcon,
} from 'lucide-react'

// Tools reference an icon by string key in the config; this maps to the component.
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  apple: Command,
  'book-open': BookOpen,
  boxes: Boxes,
  bug: Bug,
  'clipboard-list': ClipboardList,
  code: Code,
  coffee: Coffee,
  container: Container,
  database: Database,
  eye: Eye,
  figma: Frame,
  gauge: Gauge,
  gem: Gem,
  'git-branch': GitBranch,
  'git-pull-request': GitPullRequest,
  hexagon: Hexagon,
  'key-round': KeyRound,
  'layout-grid': LayoutGrid,
  'message-circle': MessageCircle,
  monitor: Monitor,
  package: Package,
  'package-2': Package2,
  'package-check': PackageCheck,
  palette: Palette,
  rocket: Rocket,
  scissors: Scissors,
  shield: ShieldCheck,
  hash: Hash,
  ship: Ship,
  smartphone: Smartphone,
  stethoscope: Stethoscope,
  terminal: Terminal,
  users: Users,
  zap: Zap,
}

export function toolIcon(key: string): LucideIcon {
  return ICONS[key] ?? Package
}
